### ISSUE TITLE
CCVR implements

### ISSUE THREAD

**Issue by xujli** [wnma3mz/flearn#1]
In the paper, the virtual representation samples are generated by covariance matrices. But in your implements, only variance matrices are calculated. 
BTW, the covariance matrix in multivariate normal distribution should be positive defined. I always encounter the error that the global cov is not PD in my implements.

**Comment by wnma3mz** [comment]
Thank you for your interest in this project.

You are correct in that I am choosing a quick and easy way to reproduce it here. I want to wait until the reproduction of the original paper before making improvements.
In fact, this method is also valid here (but no specific comparison with the original paper's method can be made for now)

Finally, can this error reporting be posted with a full description? Some code I have not yet updated to git, so maybe there are some problems

**Comment by xujli** [comment]
I don't get this sentence "Finally, can this error reporting be posted with a full description?", may you explain it. 
Moreover, in line 143 of your CCVR implement file, you use the mean value instead of cov(or var), is that correct? 
Numpy implements of distribution generation is more efficient, Torch implements is sometimes weird. I will change the corresponding code and share my implements after certain performance improvement and no error reporting.

**Comment by xujli** [comment]
I don't get this sentence "Finally, can this error reporting be posted with a full description?", may you explain it. 
Moreover, in line 143 of your CCVR implement file, you use the mean value instead of cov(or var), is that correct? 
Numpy implements of distribution generation is more efficient, Torch implements is sometimes weird. I will change the corresponding code and share my implements after certain performance improvement and no error reporting.

**Comment by wnma3mz** [comment]
1. "I always encounter the error that the global cov is not PD in my implements.". I thought you were having some problems running my side of the code
2. This is not entirely correct, at least not in the way the original paper was done. But I experimented with this code and it still works.
3. yep, another reason for using numpy is that I tried some other tools in `sklearn.decomposition` that are more convenient

**Comment by xujli** [comment]
1. I just complain about my own implements hhh.
2. I think the reason is probably that the aggregated statistical info still shows the better representation than that of the client local info, although it is biased.

**Comment by wnma3mz** [comment]
I can't agree more.

If you have any ideas that you would like to communicate further, you could contact this email address, wnma3mz@gmail.com

**Comment by xujli** [comment]
If we igonre the correlation among variables(features), we need to modify the calculation of global variance. As there is no correlation, they are all independent, simpliy summing them up with the weight is the proper way.

**Comment by xujli** [comment]
It's pleasure to share information and intuitive idea, we can chat on Wechat, my phone number is 15116362120. I'll close this issue.
